# Generated by Django 2.1.1 on 2018-09-23 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_table_2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='table_2',
        ),
    ]
